"""initial schema

Revision ID: 2a6d174f3e49
Revises: 
Create Date: 2026-07-19 07:17:18.296582

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2a6d174f3e49"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blocked_ips",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ip_address", sa.String(length=50), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("blocked_ips", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_blocked_ips_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_blocked_ips_ip_address"), ["ip_address"], unique=True
        )

    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("src_ip", sa.String(length=50), nullable=False),
        sa.Column("src_port", sa.Integer(), nullable=True),
        sa.Column("dest_ip", sa.String(length=50), nullable=False),
        sa.Column("dest_port", sa.Integer(), nullable=True),
        sa.Column("protocol", sa.String(length=20), nullable=False),
        sa.Column("flow_id", sa.Integer(), nullable=True),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_events_dest_ip"), ["dest_ip"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_events_event_type"), ["event_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_events_flow_id"), ["flow_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_events_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_src_ip"), ["src_ip"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_events_timestamp"), ["timestamp"], unique=False
        )

    op.create_table(
        "rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sid", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_custom", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("rules", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_rules_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_rules_sid"), ["sid"], unique=True)

    op.create_table(
        "statistics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("alerts_total", sa.Integer(), nullable=False),
        sa.Column("alerts_critical", sa.Integer(), nullable=False),
        sa.Column("alerts_high", sa.Integer(), nullable=False),
        sa.Column("bytes_in", sa.Integer(), nullable=False),
        sa.Column("bytes_out", sa.Integer(), nullable=False),
        sa.Column("packets_in", sa.Integer(), nullable=False),
        sa.Column("packets_out", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("statistics", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_statistics_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_statistics_timestamp"), ["timestamp"], unique=True
        )

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_users_username"), ["username"], unique=True
        )

    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("signature_id", sa.Integer(), nullable=True),
        sa.Column("signature", sa.String(length=512), nullable=False),
        sa.Column("src_ip", sa.String(length=45), nullable=False),
        sa.Column("src_port", sa.Integer(), nullable=True),
        sa.Column("dst_ip", sa.String(length=45), nullable=False),
        sa.Column("dst_port", sa.Integer(), nullable=True),
        sa.Column("protocol", sa.String(length=10), nullable=True),
        sa.Column("flow_id", sa.String(length=32), nullable=True),
        sa.Column("geo_country", sa.String(length=100), nullable=True),
        sa.Column("geo_city", sa.String(length=100), nullable=True),
        sa.Column("geo_lat", sa.Float(), nullable=True),
        sa.Column("geo_lon", sa.Float(), nullable=True),
        sa.Column("geo_org", sa.String(length=255), nullable=True),
        sa.Column("raw_eve", sa.JSON(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("acknowledged_by", sa.Integer(), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["acknowledged_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.create_index("idx_alerts_status_partial", ["status"], unique=False)
        batch_op.create_index(
            "idx_alerts_timestamp_severity", ["timestamp", "severity"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_alerts_category"), ["category"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_alerts_dst_port"), ["dst_port"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_alerts_flow_id"), ["flow_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_alerts_protocol"), ["protocol"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_alerts_severity"), ["severity"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_alerts_signature_id"), ["signature_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_alerts_src_ip"), ["src_ip"], unique=False)
        batch_op.create_index(batch_op.f("ix_alerts_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_alerts_timestamp"), ["timestamp"], unique=False
        )

    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("alert_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("details", sa.String(length=500), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["alert_id"], ["alerts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_logs_id"), ["id"], unique=False)

    op.create_table(
        "response_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("alert_id", sa.Integer(), nullable=True),
        sa.Column("handler_name", sa.String(length=50), nullable=False),
        sa.Column("action_taken", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["alert_id"], ["alerts.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("response_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_response_logs_id"), ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("response_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_response_logs_id"))

    op.drop_table("response_logs")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_logs_id"))

    op.drop_table("audit_logs")
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_alerts_timestamp"))
        batch_op.drop_index(batch_op.f("ix_alerts_status"))
        batch_op.drop_index(batch_op.f("ix_alerts_src_ip"))
        batch_op.drop_index(batch_op.f("ix_alerts_signature_id"))
        batch_op.drop_index(batch_op.f("ix_alerts_severity"))
        batch_op.drop_index(batch_op.f("ix_alerts_protocol"))
        batch_op.drop_index(batch_op.f("ix_alerts_flow_id"))
        batch_op.drop_index(batch_op.f("ix_alerts_dst_port"))
        batch_op.drop_index(batch_op.f("ix_alerts_category"))
        batch_op.drop_index("idx_alerts_timestamp_severity")
        batch_op.drop_index("idx_alerts_status_partial")

    op.drop_table("alerts")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))
        batch_op.drop_index(batch_op.f("ix_users_id"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("statistics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_statistics_timestamp"))
        batch_op.drop_index(batch_op.f("ix_statistics_id"))

    op.drop_table("statistics")
    with op.batch_alter_table("rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rules_sid"))
        batch_op.drop_index(batch_op.f("ix_rules_id"))

    op.drop_table("rules")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_timestamp"))
        batch_op.drop_index(batch_op.f("ix_events_src_ip"))
        batch_op.drop_index(batch_op.f("ix_events_id"))
        batch_op.drop_index(batch_op.f("ix_events_flow_id"))
        batch_op.drop_index(batch_op.f("ix_events_event_type"))
        batch_op.drop_index(batch_op.f("ix_events_dest_ip"))

    op.drop_table("events")
    with op.batch_alter_table("blocked_ips", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_blocked_ips_ip_address"))
        batch_op.drop_index(batch_op.f("ix_blocked_ips_id"))

    op.drop_table("blocked_ips")
    # ### end Alembic commands ###
